version: "3.2"
services:
  apache:
    container_name: bibgir
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache-bibgir.entryPoints=web,websecure"
      - "traefik.http.routers.apache-bibgir.rule=Host(`bibgir.deckle.local`)"
      - "traefik.http.services.apache-bibgir.loadbalancer.server.port=80"
      - "traefik.tcp.routers.xdebug-bibgir.rule=HostSNI(`xdebug.bibgir.deckle.local`)"
      - "traefik.tcp.routers.xdebug-bibgir.entryPoints=xdebug"
      - "traefik.tcp.services.xdebug-bibgir.loadbalancer.server.port=9000"
    build: './containers/apache/'
    #ports:
    #  - "${APACHE_PORT}:80"
    volumes:
      - ~/.composer:/root/.composer
    environment:
      PHP_IDE_CONFIG: serverName=${COMPOSE_PROJECT_NAME}

networks:
  default:
    external:
      name: common
