version: "3.2"
services:
  apache:
    container_name: conf<project.name>
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.apache-conf<project.name>.entryPoints=web,websecure"
      - "traefik.http.routers.apache-conf<project.name>.rule=Host(`conf<project.name>.deckle.local`)"
      - "traefik.http.services.apache-conf<project.name>.loadbalancer.server.port=80"
      - "traefik.tcp.routers.xdebug-conf<project.name>.rule=HostSNI(`xdebug.conf<project.name>.deckle.local`)"
      - "traefik.tcp.routers.xdebug-conf<project.name>.entryPoints=xdebug"
      - "traefik.tcp.services.xdebug-conf<project.name>.loadbalancer.server.port=9000"
    build: './containers/apache/'
    #ports:
    #  - "${APACHE_PORT}:80"
    volumes:
      - ~/.composer:/root/.composer
    environment:
      PHP_IDE_CONFIG: serverName=${COMPOSE_PROJECT_NAME}

networks:
  default:
    external:
      name: common
