services:
  _defaults:
    autowire: true
    autoconfigure: true

  Adimeo\Deckle\:
    resource: '../src'

  Symfony\Component\Console\Application:
    public: true

  Adimeo\Deckle\Deckle:
    public: true
