version: "3.2"
services:
  apache:
    build: './containers/apache/'
    depends_on:
      - mysql
    networks:
      - frontend
      - backend
    ports:
      - "${APACHE_PORT}:80"
    environment:
      PHP_IDE_CONFIG: serverName=bibgir
  mysql:
    build: './containers/mysql/'
    volumes:
      - ${COMPOSE_PROJECT_NAME}-db:/var/lib/mysql:delegated
    networks:
      - backend
    ports:
      - "${MYSQL_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  pma:
    image: phpmyadmin/phpmyadmin
    networks:
      - backend
      - frontend
    environment:
      PMA_HOST: ${PMA_HOST}
      PMA_PORT: ${PMA_PORT}
      PMA_USER: root
      PMA_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      PHP_UPLOAD_MAX_FILESIZE: ${PHP_UPLOAD_MAX_FILESIZE}
      PHP_MAX_INPUT_VARS: ${PHP_MAX_INPUT_VARS}
    ports:
      - "${PMA_HTTP_PORT}:80"

networks:
  frontend:
  backend:

volumes:
  - ${COMPOSE_PROJECT_NAME}-db:/var/lib/mysql:delegated
